name: Deploy Theme

on:
  push:
    branches:
      - staging-site-cp

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make deploy.sh executable
        run: chmod +x deploy.sh

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to appropriate environment
        env:
          CP_SFTP_HOST_STAGING: ${{ secrets.CP_SFTP_HOST_STAGING }}
          CP_SFTP_USER_STAGING: ${{ secrets.CP_SFTP_USER_STAGING }}
          CP_SFTP_PASS_STAGING: ${{ secrets.CP_SFTP_PASS_STAGING }}
        run: |
          if [[ $GITHUB_REF == "refs/heads/staging-site-cp" ]]; then
            echo "Deploying to CP staging site..."            
            ./deploy.sh staging-site-cp
          else
            echo "No matching branch. Skipping deployment."
          fi