name: Deploy Theme

on:
  push:
    branches:
      - staging-site-cp
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make deploy.sh executable
        run: chmod +x deploy.sh

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to appropriate environment
        env:
          # CP STAGING VARS
          CP_SFTP_HOST_STAGING: ${{ secrets.CP_SFTP_HOST_STAGING }}
          CP_SFTP_USER_STAGING: ${{ secrets.CP_SFTP_USER_STAGING }}
          CP_SFTP_PASS_STAGING: ${{ secrets.CP_SFTP_PASS_STAGING }}
          
          # CP PRODUCTION VARS
          CP_SFTP_HOST_PRODUCTION: ${{ secrets.CP_SFTP_HOST_PRODUCTION }}
          CP_SFTP_USER_PRODUCTION: ${{ secrets.CP_SFTP_USER_PRODUCTION }}
          CP_SFTP_PASS_PRODUCTION: ${{ secrets.CP_SFTP_PASS_PRODUCTION }}     
          
          # QW STAGING VARS
          QW_SFTP_HOST_STAGING: ${{ secrets.QW_SFTP_HOST_STAGING }}
          QW_SFTP_USER_STAGING: ${{ secrets.QW_SFTP_USER_STAGING }}
          QW_SFTP_PASS_STAGING: ${{ secrets.QW_SFTP_PASS_STAGING }}
          
          # QW PRODUCTION VARS
          QW_SFTP_HOST_PRODUCTION: ${{ secrets.QW_SFTP_HOST_PRODUCTION }}
          QW_SFTP_USER_PRODUCTION: ${{ secrets.QW_SFTP_USER_PRODUCTION }}
          QW_SFTP_PASS_PRODUCTION: ${{ secrets.QW_SFTP_PASS_PRODUCTION }}
          
          # WH STAGING VARS
          WH_SFTP_HOST_STAGING: ${{ secrets.WH_SFTP_HOST_STAGING }}
          WH_SFTP_USER_STAGING: ${{ secrets.WH_SFTP_USER_STAGING }}
          WH_SFTP_PASS_STAGING: ${{ secrets.WH_SFTP_PASS_STAGING }}
          
          # WH PRODUCTION VARS
          WH_SFTP_HOST_PRODUCTION: ${{ secrets.WH_SFTP_HOST_PRODUCTION }}
          WH_SFTP_USER_PRODUCTION: ${{ secrets.WH_SFTP_USER_PRODUCTION }}
          WH_SFTP_PASS_PRODUCTION: ${{ secrets.WH_SFTP_PASS_PRODUCTION }}
          
          # GS STAGING VARS
          GS_SFTP_HOST_STAGING: ${{ secrets.GS_SFTP_HOST_STAGING }}
          GS_SFTP_USER_STAGING: ${{ secrets.GS_SFTP_USER_STAGING }}
          GS_SFTP_PASS_STAGING: ${{ secrets.GS_SFTP_PASS_STAGING }}
          
          # GS PRODUCTION VARS
          GS_SFTP_HOST_PRODUCTION: ${{ secrets.GS_SFTP_HOST_PRODUCTION }}
          GS_SFTP_USER_PRODUCTION: ${{ secrets.GS_SFTP_USER_PRODUCTION }}
          GS_SFTP_PASS_PRODUCTION: ${{ secrets.GS_SFTP_PASS_PRODUCTION }}
        run: |
          if [[ $GITHUB_REF == "refs/heads/staging-site-cp" ]]; then
            echo "Deploying to CP staging site..."            
            ./deploy.sh staging-site-cp
          elif [[ $GITHUB_REF == "refs/heads/staging" ]]; then
            echo "Deploying to staging sites..."
            ./deploy.sh staging-sites
          elif [[ $GITHUB_REF == "refs/heads/main" ]]; then
            echo "Deploying to production sites..."
            ./deploy.sh production-sites
          else
            echo "No matching branch. Skipping deployment."
          fi
